# Generated by Django 4.2.11 on 2024-03-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_post_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='booking_time',
            field=models.DateTimeField(choices=[('18:00', '6:00PM'), ('19:00', '7:00PM'), ('20:00', '10:00PM'), ('21:00', '9:00PM'), ('22:00', '10:00PM')]),
        ),
    ]
