# Generated by Django 4.2.11 on 2024-03-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_post_author_post_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='booking_time',
            field=models.TimeField(),
        ),
    ]
