# Generated by Django 4.2.11 on 2024-03-07 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_post_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='party_size',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2, message='Value must be at least 2'), django.core.validators.MaxValueValidator(6, message='Value must be at most 6')]),
        ),
    ]
