# Generated by Django 4.2.11 on 2024-03-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_post_party_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
