# Generated by Django 4.2.11 on 2024-03-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Awaiting Arrival'), (1, 'In-Progress'), (2, 'Complete/Paid')], default=0),
        ),
    ]
